// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Race.DATA.Models
{
    public partial class Pilots
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int Age { get; set; }
        [Required]
        [StringLength(1)]
        public string Genre { get; set; }
        [Required]
        [StringLength(50)]
        public string Equip { get; set; }
        [Required]
        [StringLength(50)]
        public string Model { get; set; }
    }
}